'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { formatPercentage } from '@/lib/locale';

type CohortData = {
  cohortMonth: string;
  cohortSize: number;
  retention: {
    [key: string]: number;
  };
};

type MetricType = 'retention' | 'revenue' | 'engagement';

/**
 * Cohort Analysis View Component
 * Displays customer retention metrics in a cohort table
 */
export function CohortAnalysisView() {
  const [cohortData, setCohortData] = useState<CohortData[]>([]);
  const [metric, setMetric] = useState<MetricType>('retention');
  const [period, setPeriod] = useState<'monthly' | 'weekly'>('monthly');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchCohortData();
  }, [metric, period]);

  const fetchCohortData = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/analytics/cohorts?metric=${metric}&period=${period}`);

      if (!response.ok) {
        throw new Error('Failed to fetch cohort data');
      }

      const data = await response.json();
      setCohortData(data.cohorts || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <CohortAnalysisSkeleton />;
  }

  if (error) {
    return (
      <Card>
        <CardContent className="p-6">
          <p className="text-destructive">Error loading cohort data: {error}</p>
        </CardContent>
      </Card>
    );
  }

  // Calculate max periods to display
  const maxPeriods = Math.max(
    ...cohortData.map((cohort) => Object.keys(cohort.retention).length)
  );

  return (
    <div className="space-y-6">
      {/* Controls */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Cohort Settings</CardTitle>
              <CardDescription>Configure cohort analysis parameters</CardDescription>
            </div>
            <div className="flex gap-4">
              <Select value={metric} onValueChange={(v) => setMetric(v as MetricType)}>
                <SelectTrigger className="w-[180px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="retention">Retention Rate</SelectItem>
                  <SelectItem value="revenue">Revenue per Cohort</SelectItem>
                  <SelectItem value="engagement">Engagement Rate</SelectItem>
                </SelectContent>
              </Select>

              <Select value={period} onValueChange={(v) => setPeriod(v as 'monthly' | 'weekly')}>
                <SelectTrigger className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="monthly">Monthly</SelectItem>
                  <SelectItem value="weekly">Weekly</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Cohort Table */}
      <Card>
        <CardHeader>
          <CardTitle>Cohort Retention Matrix</CardTitle>
          <CardDescription>
            {metric === 'retention' && 'Percentage of customers who remain active'}
            {metric === 'revenue' && 'Revenue generated by each cohort over time'}
            {metric === 'engagement' && 'Engagement rate by cohort over time'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {cohortData.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              No cohort data available. Start acquiring customers to see retention metrics.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="border-b">
                    <th className="p-3 text-left font-semibold">Cohort</th>
                    <th className="p-3 text-right font-semibold">Size</th>
                    {Array.from({ length: maxPeriods }).map((_, i) => (
                      <th key={i} className="p-3 text-right font-semibold">
                        {period === 'monthly' ? `Month ${i}` : `Week ${i}`}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {cohortData.map((cohort) => (
                    <tr key={cohort.cohortMonth} className="border-b hover:bg-muted/50">
                      <td className="p-3 font-medium">{cohort.cohortMonth}</td>
                      <td className="p-3 text-right">{cohort.cohortSize.toLocaleString()}</td>
                      {Array.from({ length: maxPeriods }).map((_, i) => {
                        const value = cohort.retention[i.toString()];
                        if (value === undefined) {
                          return <td key={i} className="p-3 text-right text-muted-foreground">—</td>;
                        }

                        // Color coding based on retention percentage
                        let bgColor = 'bg-muted';
                        if (metric === 'retention') {
                          if (value >= 80) bgColor = 'bg-green-100 dark:bg-green-900/30';
                          else if (value >= 60) bgColor = 'bg-green-50 dark:bg-green-900/20';
                          else if (value >= 40) bgColor = 'bg-yellow-50 dark:bg-yellow-900/20';
                          else if (value >= 20) bgColor = 'bg-orange-50 dark:bg-orange-900/20';
                          else bgColor = 'bg-red-50 dark:bg-red-900/20';
                        }

                        return (
                          <td key={i} className={`p-3 text-right ${bgColor}`}>
                            {metric === 'retention'
                              ? formatPercentage(value)
                              : value.toLocaleString()}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Insights */}
      {cohortData.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Key Insights</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="p-4 rounded-lg border">
                <p className="text-sm text-muted-foreground">Avg. Month 0 Retention</p>
                <p className="text-2xl font-bold mt-1">
                  {formatPercentage(
                    cohortData.reduce((acc, c) => acc + (c.retention['0'] || 0), 0) /
                      cohortData.length
                  )}
                </p>
              </div>
              <div className="p-4 rounded-lg border">
                <p className="text-sm text-muted-foreground">Avg. Month 3 Retention</p>
                <p className="text-2xl font-bold mt-1">
                  {formatPercentage(
                    cohortData.reduce((acc, c) => acc + (c.retention['3'] || 0), 0) /
                      cohortData.filter((c) => c.retention['3'] !== undefined).length
                  )}
                </p>
              </div>
              <div className="p-4 rounded-lg border">
                <p className="text-sm text-muted-foreground">Total Customers</p>
                <p className="text-2xl font-bold mt-1">
                  {cohortData.reduce((acc, c) => acc + c.cohortSize, 0).toLocaleString()}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

/**
 * Loading skeleton for cohort analysis
 */
export function CohortAnalysisSkeleton() {
  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="h-6 w-48 bg-muted animate-pulse rounded" />
          <div className="h-4 w-96 bg-muted animate-pulse rounded mt-2" />
        </CardHeader>
      </Card>
      <Card>
        <CardContent className="p-6">
          <div className="space-y-4">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="h-12 bg-muted animate-pulse rounded" />
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
