-- Website Scraper Tables
-- Stores scraped website data for context and analysis

-- Websites being analyzed
CREATE TABLE IF NOT EXISTS websites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  url TEXT NOT NULL UNIQUE,
  domain TEXT NOT NULL,
  title TEXT,
  description TEXT,
  scrape_status TEXT DEFAULT 'pending', -- pending, in_progress, completed, failed
  pages_scraped INTEGER DEFAULT 0,
  total_pages_found INTEGER DEFAULT 0,
  last_scraped_at TIMESTAMPTZ,
  metadata JSONB, -- Additional metadata (favicon, og_image, etc.)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Individual pages from scraped websites
CREATE TABLE IF NOT EXISTS scraped_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID REFERENCES websites(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  content TEXT, -- Full text content
  html TEXT, -- Full HTML
  word_count INTEGER,
  headings JSONB, -- Array of H1-H6 headings
  links JSONB, -- Internal and external links
  images JSONB, -- Image URLs and alt text
  metadata JSONB, -- Meta tags, OG tags, etc.
  scraped_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(website_id, url)
);

CREATE INDEX IF NOT EXISTS idx_scraped_pages_website ON scraped_pages(website_id);
CREATE INDEX IF NOT EXISTS idx_scraped_pages_url ON scraped_pages(url);

-- Content gaps and opportunities identified
CREATE TABLE IF NOT EXISTS content_gaps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID REFERENCES websites(id) ON DELETE CASCADE,
  gap_type TEXT NOT NULL, -- missing_topic, thin_content, outdated_content, broken_link, poor_seo
  severity TEXT DEFAULT 'medium', -- low, medium, high, critical
  title TEXT NOT NULL,
  description TEXT,
  suggested_action TEXT,
  affected_pages JSONB, -- Array of page URLs
  metadata JSONB, -- Additional context
  status TEXT DEFAULT 'open', -- open, in_progress, resolved, ignored
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_content_gaps_website ON content_gaps(website_id);
CREATE INDEX IF NOT EXISTS idx_content_gaps_status ON content_gaps(status);

-- Content suggestions generated by AI
CREATE TABLE IF NOT EXISTS content_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID REFERENCES websites(id) ON DELETE CASCADE,
  gap_id UUID REFERENCES content_gaps(id) ON DELETE SET NULL,
  suggestion_type TEXT NOT NULL, -- new_blog_post, update_page, create_resource, add_section
  title TEXT NOT NULL,
  description TEXT,
  estimated_impact TEXT, -- high, medium, low
  target_keyword TEXT,
  estimated_word_count INTEGER,
  outline JSONB, -- Suggested structure
  reasoning TEXT, -- Why this suggestion
  priority INTEGER DEFAULT 0,
  status TEXT DEFAULT 'suggested', -- suggested, approved, in_progress, completed, rejected
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_content_suggestions_website ON content_suggestions(website_id);
CREATE INDEX IF NOT EXISTS idx_content_suggestions_status ON content_suggestions(status);

-- Website analytics and insights
CREATE TABLE IF NOT EXISTS website_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  website_id UUID REFERENCES websites(id) ON DELETE CASCADE,
  insight_type TEXT NOT NULL, -- content_distribution, topic_coverage, seo_health, internal_linking
  metric_name TEXT NOT NULL,
  metric_value JSONB,
  trend TEXT, -- improving, declining, stable
  recommendations JSONB,
  analyzed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(website_id, insight_type, metric_name)
);

CREATE INDEX IF NOT EXISTS idx_website_insights_website ON website_insights(website_id);
