-- Migration: Multiple Outline Options Feature
-- Description: Adds support for generating and storing multiple outline options
-- Created: 2026-01-13

-- Create outline_options table
CREATE TABLE IF NOT EXISTS outline_options (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blog_post_id UUID NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
  option_number INTEGER NOT NULL, -- 1, 2, or 3
  outline_data JSONB NOT NULL, -- Full outline structure
  total_estimated_words INTEGER,
  generated_at TIMESTAMPTZ DEFAULT now(),
  is_selected BOOLEAN DEFAULT false,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),

  -- Constraints
  CONSTRAINT outline_options_blog_post_option_unique UNIQUE (blog_post_id, option_number),
  CONSTRAINT outline_options_option_number_check CHECK (option_number >= 1 AND option_number <= 3)
);

-- Create index for fast lookups
CREATE INDEX idx_outline_options_blog_post_id ON outline_options(blog_post_id);
CREATE INDEX idx_outline_options_selected ON outline_options(blog_post_id, is_selected) WHERE is_selected = true;

-- Enable Row Level Security
ALTER TABLE outline_options ENABLE ROW LEVEL SECURITY;

-- RLS Policies for outline_options
-- Policy 1: Vendors can view outline options for posts they own
CREATE POLICY "Vendors can view their outline options"
  ON outline_options
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM blog_posts bp
      WHERE bp.id = outline_options.blog_post_id
      AND bp.client_id IN (
        SELECT id FROM clients WHERE vendor_user_id = auth.uid()
      )
    )
  );

-- Policy 2: Vendors can insert outline options for their posts
CREATE POLICY "Vendors can create outline options"
  ON outline_options
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM blog_posts bp
      WHERE bp.id = outline_options.blog_post_id
      AND bp.client_id IN (
        SELECT id FROM clients WHERE vendor_user_id = auth.uid()
      )
    )
  );

-- Policy 3: Vendors can update outline options for their posts
CREATE POLICY "Vendors can update their outline options"
  ON outline_options
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM blog_posts bp
      WHERE bp.id = outline_options.blog_post_id
      AND bp.client_id IN (
        SELECT id FROM clients WHERE vendor_user_id = auth.uid()
      )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM blog_posts bp
      WHERE bp.id = outline_options.blog_post_id
      AND bp.client_id IN (
        SELECT id FROM clients WHERE vendor_user_id = auth.uid()
      )
    )
  );

-- Policy 4: Vendors can delete outline options for their posts
CREATE POLICY "Vendors can delete outline options"
  ON outline_options
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM blog_posts bp
      WHERE bp.id = outline_options.blog_post_id
      AND bp.client_id IN (
        SELECT id FROM clients WHERE vendor_user_id = auth.uid()
      )
    )
  );

-- Add custom_outline field to blog_posts for storing merged/customized outlines
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS custom_outline JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS selected_outline_option_id UUID REFERENCES outline_options(id) ON DELETE SET NULL;

-- Create index for selected outline option
CREATE INDEX IF NOT EXISTS idx_blog_posts_selected_outline ON blog_posts(selected_outline_option_id) WHERE selected_outline_option_id IS NOT NULL;

-- Update timestamp trigger for outline_options
CREATE OR REPLACE FUNCTION update_outline_options_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER outline_options_updated_at
  BEFORE UPDATE ON outline_options
  FOR EACH ROW
  EXECUTE FUNCTION update_outline_options_updated_at();

-- Comments for documentation
COMMENT ON TABLE outline_options IS 'Stores multiple outline options generated by the AI for comparison and selection';
COMMENT ON COLUMN outline_options.option_number IS 'Sequential option number (1-3) for each blog post';
COMMENT ON COLUMN outline_options.outline_data IS 'Full outline structure with sections array';
COMMENT ON COLUMN outline_options.is_selected IS 'True if this option was selected by the user';
COMMENT ON COLUMN blog_posts.custom_outline IS 'User-customized outline created by merging/editing options';
COMMENT ON COLUMN blog_posts.selected_outline_option_id IS 'Reference to the selected outline option if user chose one directly';
